version: '3.8'
volumes:
  mysql-storage:
    driver: local
networks:
  internal:
    driver: bridge
services:
  app:
    build: ./app
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: desafio-dev
      MYSQL_PASSWORD: desafio-dev
      MYSQL_USER: desafio-dev
    volumes:
      - mysql-storage:/var/lib/mysql:rw
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - internal
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10